config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'books#index'
  resources :customers, :books, :authors, :orders, :reviews, :suppliers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many:books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :supplier
  belongs_to :author
  has_many :reviews
  has_and_belongs_to_many :orders, join_table: 'books_orders'
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :reviews
  has_many :orders
  # default_scope { select(:first_name).order(:first_name) }
  scope :order_between, ->(a,b) { where('order_count between ? and ?', a, b) }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_and_belongs_to_many :books, join_table: 'bookorders'
  enum status: %i[shipped being_packed complete cancelled]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  belongs_to :book
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :books
  has_many :authors, through: :books
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index 
    @authors = Author.all 
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index 
    @books = Book.all 
  end
  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all 
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index 
    @orders = Order.all 
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index 
    @reviews = Review.all 
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def index 
    @suppliers = Supplier.all 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "books", books_path %>
    <%= link_to "authors", authors_path %>
    <%= link_to "customers", customers_path %>
    <%= link_to "orders", orders_path %>
    <%= link_to "reviews", reviews_path %>
    <%= link_to "suppliers", suppliers_path %>
    <%= yield %>
  </body>
</html>